parent=keycloak
import=common/keycloak

styles=css/login.css
stylesCommon=
scripts=js/neural-bg.js

meta=viewport==width=device-width,initial-scale=1

kcHtmlClass=aip-html
kcBodyClass=aip-body
kcLoginClass=aip-login
kcHeaderClass=aip-header-hidden
kcFormCardClass=aip-form-panel
kcFormHeaderClass=aip-form-header
kcFormClass=aip-form
kcFormGroupClass=aip-form-group
kcLabelClass=aip-label
kcLabelWrapperClass=aip-label-wrap
kcInputClass=aip-input
kcInputWrapperClass=aip-input-wrap
kcInputGroup=aip-input-group
kcInputErrorMessageClass=aip-input-error
kcFormPasswordVisibilityButtonClass=aip-eye-btn
kcFormPasswordVisibilityIconShow=fa fa-eye
kcFormPasswordVisibilityIconHide=fa fa-eye-slash
kcFormSettingClass=aip-form-settings
kcFormOptionsClass=aip-form-options
kcFormOptionsWrapperClass=aip-form-options-wrap
kcFormButtonsClass=aip-form-buttons
kcButtonClass=aip-btn
kcButtonPrimaryClass=aip-btn-primary
kcButtonBlockClass=aip-btn-block
kcButtonLargeClass=
kcAlertClass=aip-alert
kcAlertTitleClass=aip-alert-title
kcFeedbackErrorIcon=fa fa-fw fa-exclamation-circle
kcFeedbackWarningIcon=fa fa-fw fa-exclamation-triangle
kcFeedbackSuccessIcon=fa fa-fw fa-check-circle
kcFeedbackInfoIcon=fa fa-fw fa-info-circle
kcSignUpClass=aip-info
kcInfoAreaWrapperClass=aip-info-wrap
kcFormSocialAccountSectionClass=aip-social
kcFormSocialAccountListClass=aip-social-list
kcFormSocialAccountListButtonClass=aip-social-btn
kcLocaleMainClass=aip-locale
kcLocaleListClass=aip-locale-list
kcLocaleItemClass=aip-locale-item
kcResetFlowIcon=pficon pficon-arrow fa
